{
 "title": "ClamAV Scan Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values({job=\"clamav\"}, host)"
   }
  ]
 },
 "panels": [
  {
   "title": "Infected Files",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"clamav\", host=\"$host\"} |= `Infected files:` | regexp `Infected files: (?P<files>[0-9]+)`"
    }
   ]
  },
  {
   "title": "Infected Files 2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "max by (host) ( last_over_time({job=\"clamav\", host=\"$host\"} |= \"Infected\" | regexp \"Infected files: (?P<Infected>[0-9]+)\" | unwrap Infected [3640d]) )",
     "legendFormat": "{{files}}"
    }
   ]
  },
  {
   "title": "Scanned Directories",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "max by (host) ( last_over_time({job=\"clamav\", host=\"$host\"} |= \"Scanned directories:\" | regexp \"Scanned directories: (?P<directories>[0-9]+)\" | unwrap directories [3640d]) )",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Scanned Files",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "max by (host) ( last_over_time({job=\"clamav\", host=\"$host\"} |= \"Scanned files:\" | regexp \"Scanned files: (?P<files>[0-9]+)\" | unwrap files [3640d]) )",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Last Scan Duration (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "direction": "backward",
     "expr": "max by (host) ( last_over_time({job=\"clamav\", host=\"$host\"} |= \"Time:\" | regexp \"Time: (?P<duration>[0-9.]+)\" | unwrap duration [3640d]) )",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Known Viruses",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "direction": "backward",
     "expr": "max by (host) ( last_over_time({job=\"clamav\", host=\"$host\"} |= \"Known viruses:\" | regexp \"Known viruses: (?P<viruses>[0-9]+)\" | unwrap viruses [3640d]) )",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "ClamAV Version Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"clamav\",host=\"$host\"} |= `Version`",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}