services:
  erpnext-backend:
    container_name: erpnext-backend
    image: frappe/erpnext:v16.25.0
    restart: unless-stopped
    networks:
      - frappe_network
    volumes:
      - /mnt/DriveDATA/erpnext/sites:/home/frappe/frappe-bench/sites
      - /mnt/DriveDATA/erpnext/logs:/home/frappe/frappe-bench/logs
    environment:
      DB_HOST: erpnext-db
      DB_PORT: "3306"
      MYSQL_ROOT_PASSWORD: aPUo56ZCWR
      MARIADB_ROOT_PASSWORD: aPUo56ZCWR

  erpnext-configurator:
    container_name: erpnext-configurator
    image: frappe/erpnext:v16.25.0
    restart: "no"
    networks:
      - frappe_network
    entrypoint:
      - bash
      - -c
    command:
      - >
        ls -1 apps > sites/apps.txt;
        bench set-config -g db_host $$DB_HOST;
        bench set-config -gp db_port $$DB_PORT;
        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
        bench set-config -gp socketio_port $$SOCKETIO_PORT;
    environment:
      DB_HOST: erpnext-db
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: "9000"
    volumes:
      - /mnt/DriveDATA/erpnext/sites:/home/frappe/frappe-bench/sites
      - /mnt/DriveDATA/erpnext/logs:/home/frappe/frappe-bench/logs

  erpnext-create-site:
    container_name: erpnext-create-site
    image: frappe/erpnext:v16.25.0
    restart: "no"
    networks:
      - frappe_network
    entrypoint:
      - bash
      - -c
    command:
      - >
        wait-for-it -t 120 erpnext-db:3306;
        wait-for-it -t 120 redis-cache:6379;
        wait-for-it -t 120 redis-queue:6379;
        export start=`date +%s`;
        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
        do
          echo "Waiting for sites/common_site_config.json to be created";
          sleep 5;
          if (( `date +%s`-start > 120 )); then
            echo "could not find sites/common_site_config.json with required keys";
            exit 1;
          fi;
        done;
        echo "sites/common_site_config.json found";
        bench new-site \
          --mariadb-user-host-login-scope='%' \
          --admin-password=admin \
          --db-root-username=root \
          --db-root-password=aPUo56ZCWR \
          --install-app erpnext \
          --set-default frontend;
    volumes:
      - /mnt/DriveDATA/erpnext/sites:/home/frappe/frappe-bench/sites
      - /mnt/DriveDATA/erpnext/logs:/home/frappe/frappe-bench/logs

  erpnext-db:
    container_name: erpnext-db
    image: mariadb:11.8
    restart: unless-stopped
    networks:
      - frappe_network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 5
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    environment:
      MYSQL_ROOT_PASSWORD: aPUo56ZCWR
      MARIADB_ROOT_PASSWORD: aPUo56ZCWR
    volumes:
      - /mnt/DriveDATA/erpnext/db-data:/var/lib/mysql

  frontend:
    image: frappe/erpnext:v16.25.0
    restart: unless-stopped
    networks:
      - frappe_network
    depends_on:
      - websocket
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: erpnext-backend:8000
      FRAPPE_SITE_NAME_HEADER: frontend
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      - /mnt/DriveDATA/erpnext/sites:/home/frappe/frappe-bench/sites
      - /mnt/DriveDATA/erpnext/logs:/home/frappe/frappe-bench/logs
    ports:
      - "8080:8080"

  queue-long:
    image: frappe/erpnext:v16.25.0
    restart: unless-stopped
    networks:
      - frappe_network
    command:
      - bench
      - worker
      - --queue
      - long,default,short
    environment:
      FRAPPE_REDIS_CACHE: redis://redis-cache:6379
      FRAPPE_REDIS_QUEUE: redis://redis-queue:6379
    volumes:
      - /mnt/DriveDATA/erpnext/sites:/home/frappe/frappe-bench/sites
      - /mnt/DriveDATA/erpnext/logs:/home/frappe/frappe-bench/logs

  queue-short:
    image: frappe/erpnext:v16.25.0
    restart: unless-stopped
    networks:
      - frappe_network
    command:
      - bench
      - worker
      - --queue
      - short,default
    environment:
      FRAPPE_REDIS_CACHE: redis://redis-cache:6379
      FRAPPE_REDIS_QUEUE: redis://redis-queue:6379
    volumes:
      - /mnt/DriveDATA/erpnext/sites:/home/frappe/frappe-bench/sites
      - /mnt/DriveDATA/erpnext/logs:/home/frappe/frappe-bench/logs

  redis-queue:
    image: redis:6.2-alpine
    restart: unless-stopped
    networks:
      - frappe_network
    volumes:
      - /mnt/DriveDATA/erpnext/redis-queue-data:/data

  redis-cache:
    image: redis:6.2-alpine
    restart: unless-stopped
    networks:
      - frappe_network

  scheduler:
    image: frappe/erpnext:v16.25.0
    restart: unless-stopped
    networks:
      - frappe_network
    command:
      - bench
      - schedule
    volumes:
      - /mnt/DriveDATA/erpnext/sites:/home/frappe/frappe-bench/sites
      - /mnt/DriveDATA/erpnext/logs:/home/frappe/frappe-bench/logs

  websocket:
    image: frappe/erpnext:v16.25.0
    restart: unless-stopped
    networks:
      - frappe_network
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    environment:
      FRAPPE_REDIS_CACHE: redis://redis-cache:6379
      FRAPPE_REDIS_QUEUE: redis://redis-queue:6379
    volumes:
      - /mnt/DriveDATA/erpnext/sites:/home/frappe/frappe-bench/sites
      - /mnt/DriveDATA/erpnext/logs:/home/frappe/frappe-bench/logs

networks:
  frappe_network:
    driver: bridge