version: "3"

services:
  docmost:
    image: docmost/docmost:0.7.0
    depends_on:
      - db
      - redis
    environment:
      APP_URL: "https://ChangeMeAppURL"
      APP_SECRET: "ChangeMeSecKey"
      DATABASE_URL: "postgresql://bgdocmost:aPUo56ZCWR@db:5432/bgdocmost?schema=public"
      REDIS_URL: "redis://redis:6379"
      MAIL_DRIVER: "smtp"
      SMTP_HOST: "ChangeMeSMTPHOST"
      SMTP_PORT: "ChangeMePORT"
      SMTP_USERNAME: "ChangeMeUserNAME"
      SMTP_PASSWORD: "ChangeMePWD"
      MAIL_FROM_ADDRESS: "ChangeMeUserNAME"
      MAIL_FROM_NAME: "ChangeMeMailFrom"
      SMTP_SECURE: false
    ports:
      - "7091:3000"
    restart: unless-stopped
    volumes:
      - /mnt/DriveDATA/docmost/db:/app/data/storage

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: bgdocmost
      POSTGRES_USER: bgdocmost
      POSTGRES_PASSWORD: aPUo56ZCWR
    restart: unless-stopped
    volumes:
      - /mnt/DriveDATA/docmost/data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - /mnt/DriveDATA/docmost/radish:/data

#volumes:
#  docmost:
#  db_data:
#  redis_data: