node {
  stage 'Checkout code'
  checkout scm
//  def packageJSON = readJSON file: 'version.json'
//  def packageJSONVersion = packageJSON.version
//  echo packageJSONVersion

  stage 'Docker build'
  sh 'aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 747026847740.dkr.ecr.us-east-1.amazonaws.com'

  stage 'Docker push'

  if (env.BRANCH_NAME == 'main') {
    docker.build('openteche-mantisbt')
    docker.withRegistry('https://747026847740.dkr.ecr.us-east-1.amazonaws.com/') {
        docker.image('openteche-mantisbt').push('latest')
    }
  }       
}