version: '3.8'
services:
  filegator:
    container_name: filegator
    image: filegator/filegator:v7.12.0
    restart: unless-stopped
    ports:
      - "7090:8080"
    volumes:
      # Mount local folder as a repository
      - /mnt/DriveDATA/filegator/files:/var/www/filegator/repository
      # Locally stored users.json file
      - /mnt/DriveDATA/filegator/users/users.json:/var/www/filegator/private/users.json
      # Load your own custom configuration file
      #- /mnt/DriveDATA/filegator/config/configuration.php:/var/www/filegator/configuration.php