version: "2"

services:
  database:
    image: powertic/percona-docker
    container_name: mautic-database
    environment:
      MYSQL_ROOT_PASSWORD: Monday@123
    volumes:
      - /mnt/DriveDATA/mautic/database:/var/lib/mysql
    restart: unless-stopped
    networks:
      - mauticnet
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --sql-mode=""

  mautic:
    container_name: mautic
    image: mautic/mautic:v4-apache
    volumes:
      - /mnt/DriveDATA/mautic/mautic_data:/var/www/html
    environment:
      - MAUTIC_DB_HOST=mautic-database
      - MAUTIC_DB_USER=root
      - MAUTIC_DB_PASSWORD=mypassword
      - MAUTIC_DB_NAME=mautic4
    restart: unless-stopped
    networks:
      - mauticnet
    ports:
      - "8880:80"

networks:
  mauticnet:
