version: '3'

services:
  it-tools:
    image: corentinth/it-tools:2024.10.22-7ca5933
    container_name: it-tools
    ports:
      - "8220:80"
    volumes:
      - /mnt/DriveDATA/ittools/data:/data  # Persistent storage
    restart: unless-stopped

#volumes:
#  it-tools-data:
#    driver: local