version: '2'
services:
  bookstack-mysql:
    image: mysql:8.3
    environment:
      - MYSQL_ROOT_PASSWORD=monday123
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=monday123
    volumes:
      - /mnt/DriveDATA/bookstack/bookstack_mysql-data:/var/lib/mysql
    restart: unless-stopped

  bookstack:
    image: solidnerd/bookstack:24.5.2
    depends_on:
      - bookstack-mysql
    environment:
      - DB_HOST=bookstack-mysql:3306
      - DB_DATABASE=bookstack
      - DB_USERNAME=bookstack
      - DB_PASSWORD=monday123
      - APP_URL=https://bookstack.openteche.io
      - APP_KEY=SomeRandomStringWith32Characters
    volumes:
      - /mnt/DriveDATA/bookstack/bookstack_uploads:/var/www/bookstack/public/uploads
    ports:
      - "3003:8080"
    restart: unless-stopped

