version: '2'
services:
  bookstack-mysql:
    container_name: bookstack
    image: mysql:8.3
    environment:
      - MYSQL_ROOT_PASSWORD=aPUo56ZCWR
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=aPUo56ZCWR
    volumes:
      - /mnt/DriveDATA/bookstack/bookstack_mysql-data:/var/lib/mysql
    restart: unless-stopped

  bookstack:
    container_name: bookstack-database
    image: solidnerd/bookstack:24.5.2
    depends_on:
      - bookstack-mysql
    environment:
      - DB_HOST=bookstack-mysql:3306
      - DB_DATABASE=bookstack
      - DB_USERNAME=bookstack
      - DB_PASSWORD=aPUo56ZCWR
      - APP_URL=ChangeMe-APP_URL
      - APP_KEY=SomeRandomStringWith32Characters
    volumes:
      - /mnt/DriveDATA/bookstack/bookstack_uploads:/var/www/bookstack/public/uploads
    ports:
      - "7076:8080"
    restart: unless-stopped

