version: '3'
services:
    meshcentral:
        restart: unless-stopped
        container_name: meshcentral
        image: typhonragewind/meshcentral:1.1.32
        ports:
            - 7084:443  #MeshCentral will moan and try everything not to use port 80, but you can also use it if you so desire, just change the config.json according to your needs
        environment:
            - HOSTNAME=ChangeMe-APP_URL    #your hostname
            - REVERSE_PROXY=ChangeMe-APP_URL    #set to your reverse proxy IP if you want to put meshcentral behind a reverse proxy
            - REVERSE_PROXY_TLS_PORT=
            - IFRAME=false    #set to true if you wish to enable iframe support
            - ALLOW_NEW_ACCOUNTS=false    #set to false if you want disable self-service creation of new accounts besides the first (admin)
            - WEBRTC=false  #set to true to enable WebRTC - per documentation it is not officially released with meshcentral, but is solid enough to work with. Use with caution
            - BACKUPS_PW=aPUo56ZCWR #password for the autobackup function
            - BACKUP_INTERVAL=24 # Interval in hours for the autobackup function
            - BACKUP_KEEP_DAYS=10 #number of days of backups the function keeps
        volumes:
            - /mnt/DriveDATA/meshcentral/data:/opt/meshcentral/meshcentral-data    #config.json and other important files live here. A must for data persistence
            - /mnt/DriveDATA/meshcentral/user_files:/opt/meshcentral/meshcentral-files    #where file uploads for users live
            - /mnt/DriveDATA/meshcentral/backups:/opt/meshcentral/meshcentral-backups     #Backups location
