version: '3'
services:
  app:
    container_name: mycloudapp-server
    image: nextcloud:fpm
    restart: always
    expose:
      - '80'
      - '9000'
    volumes:
      - /mnt/DriveDATA/nextcloud/app_data:/var/www/html
  onlyoffice-document-server:
    container_name: mycloudapp-onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    restart: always
    environment:
      - JWT_SECRET=secret
    expose:
      - '80'
      - '443'
    volumes:
      - /mnt/DriveDATA/nextcloud/document_data:/var/www/onlyoffice/Data
      - /mnt/DriveDATA/nextcloud/document_log:/var/log/onlyoffice
  nginx:
    container_name: mycloudapp-nginx-server
    image: nginx
    restart: always
    ports:
      - 4000:80
      - 4001:443
    volumes:
      - /mnt/DriveDATA/nextcloud/nginx.conf:/etc/nginx/nginx.conf
      - /mnt/DriveDATA/nextcloud/app_data:/var/www/html
