services:

  espocrm-db:
    image: mariadb:11.8
    container_name: espocrm-db
    environment:
      MARIADB_ROOT_PASSWORD: aPUo56ZCWR
      MARIADB_DATABASE: espocrm
      MARIADB_USER: espocrm
      MARIADB_PASSWORD: aPUo56EsPOZCWR
    volumes:
      - /mnt/DriveDATA/espocrm/db:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  espocrm:
    image: espocrm/espocrm:9.3.8-apache
    container_name: espocrm
    environment:
      ESPOCRM_DATABASE_PLATFORM: Mysql
      ESPOCRM_DATABASE_HOST: espocrm-db
      ESPOCRM_DATABASE_USER: espocrm
      ESPOCRM_DATABASE_PASSWORD: aPUo56EsPOZCWR
      ESPOCRM_ADMIN_USERNAME: admin
      ESPOCRM_ADMIN_PASSWORD: admin
    volumes:
      - /mnt/DriveDATA/espocrm/data:/var/www/html
    restart: unless-stopped
    depends_on:
      espocrm-db:
        condition: service_healthy
    ports:
      - "8241:80"

  espocrm-daemon:
    image: espocrm/espocrm:9.3.8-apache
    container_name: espocrm-daemon
    volumes:
      - /mnt/DriveDATA/espocrm/data:/var/www/html
    restart: unless-stopped
    entrypoint: docker-daemon.sh
    depends_on:
      - espocrm

  espocrm-websocket:
    image: espocrm/espocrm:9.3.8-apache
    container_name: espocrm-websocket
    environment:
      ESPOCRM_CONFIG_USE_WEB_SOCKET: "true"
      ESPOCRM_CONFIG_WEB_SOCKET_URL: "ws://localhost:8242"
      ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBSCRIBER_DSN: "tcp://*:7777"
      ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBMISSION_DSN: "tcp://espocrm-websocket:7777"
    volumes:
      - /mnt/DriveDATA/espocrm/data:/var/www/html
    restart: unless-stopped
    entrypoint: docker-websocket.sh
    ports:
      - "8242:8080"
    depends_on:
      - espocrm