FROM jenkins/jenkins:lts-jdk17
USER root

# Install Docker CLI
RUN apt-get update && \
    apt-get install -y docker.io

# Match Docker group ID with host (if needed), then add Jenkins to the group
RUN groupmod -g 110 docker || true && \
    usermod -aG docker jenkins

USER jenkins
