#!/bin/bash

# Variables
LOG_FILE="/var/log/clamav_scan_$(date +%F_%H-%M-%S).txt"
REMOTE_USER="root"  # Remote server username
REMOTE_HOST="dash.teche.ai"  # Remote server hostname or IP
REMOTE_PATH="/var/www/html/scans"  # Destination path on remote server
REMOTE_KEY="/home/admin/key/teche.ai"

# Update ClamAV database
echo "Updating ClamAV database..."
sudo freshclam

# Run ClamAV scan on root directory
echo "Starting ClamAV scan on / ..."
sudo clamscan -ri /home/admin/apps --bell --log="$LOG_FILE"
chmod 644 $LOG_FILE


# Transfer report to remote server (comment this incase save locally)
echo "Transferring scan report to remote server..."
scp -i "$REMOTE_KEY" -o StrictHostKeyChecking=no "$LOG_FILE" "$REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH"


# Verify transfer success
if [ $? -eq 0 ]; then
    echo "Scan report successfully transferred to $REMOTE_HOST:$REMOTE_PATH"
else
    echo "Failed to transfer scan report."
fi

# Cleanup: Remove old logs (optional)
find /var/log -name "clamav_scan_*.log" -mtime +7 -delete

echo "ClamAV scan and report transfer completed."
