version: "3.8"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    ports:
      - "8240:3001"  # Host port 8240 maps to container's 3001
    volumes:
      - /mnt/DriveDATA/uptime-kuma:/app/data
    restart: unless-stopped