version: '3.5'

services:

  akaunting:
    container_name: akaunting
    image: docker.io/akaunting/akaunting:3
    ports:
      - 7070:80
      - 7071:443
    volumes:
      - /mnt/DriveDATA/akaunting/data:/var/www/html/akaunting
      - /mnt/DriveDATA/akaunting/apache:/etc/apache2/sites-available
      - /mnt/DriveDATA/akaunting/letsencrypt:/etc/letsencrypt
      - /mnt/DriveDATA/akaunting/letsencrypt_lib:/var/lib/letsencrypt
    restart: unless-stopped
    depends_on:
      - akaunting-db

  akaunting-db:
    image: mariadb:11.5.2
    container_name: akaunting-db
    environment:
      MYSQL_ROOT_PASSWORD: aPUo56ZCWR
      MYSQL_DATABASE: accounts
      MYSQL_USER: techeakaunt
      MYSQL_PASSWORD: aPUo56ZCWR
    volumes:
      - /mnt/DriveDATA/akaunting/akaunting-db:/var/lib/mysql
    restart: unless-stopped