version: "3.8"

services:
    mantisbt:
        image: xlrl/mantisbt:2.26.3
        container_name: techeBT-frontend
        environment:
            MANTIS_TIMEZONE: Asia/Kolkata
            MANTIS_ENABLE_ADMIN: 1
        ports:
            - "3001:80"
        volumes:
            - /mnt/DriveDATA/mantis/html/config:/var/www/html/config
            - /mnt/DriveDATA/mantis/html/custom:/var/www/html/custom    
            - /mnt/DriveDATA/mantis/html/plugins:/var/www/html/plugins
        restart: unless-stopped

    mysql:
        image: mariadb:11.5.2
        container_name: techeBT-database
        environment:
            MYSQL_ROOT_PASSWORD: aPUo56ZCWR
            MYSQL_DATABASE: techebttracker
            MYSQL_USER: techebt
            MYSQL_PASSWORD: aPUo56ZCWR
        volumes:
            - /mnt/DriveDATA/mantis/lib/mysql:/var/lib/mysql
        restart: unless-stopped