version: "3.8"

services:
    mantisbt:
        image: techeai/techebt:2.26.3
        container_name: techeBT-frontend
        ports:
            - "3001:80"
        volumes:
            - /mnt/DriveDATA/mantis/html:/home/ubuntu/public_html
        restart: unless-stopped

    mysql:
        image: mariadb:11.5.2
        container_name: techeBT-database
        environment:
            MYSQL_ROOT_PASSWORD: aPUo56ZCWR
            MYSQL_DATABASE: techebttracker
            MYSQL_USER: techebt
            MYSQL_PASSWORD: aPUo56ZCWR
            MARIADB_CHARACTER_SET_SERVER: utf8mb4
            MARIADB_COLLATION_SERVER: utf8mb4_general_ci
        volumes:
            - /mnt/DriveDATA/mantis/db:/var/lib/mysql
        restart: unless-stopped