version: "3.8"

services:
    mantisbt:
        image: xlrl/mantisbt:2.26.3
        environment:
            MANTIS_TIMEZONE: Europe/Berlin
            MANTIS_ENABLE_ADMIN: 0
        ports:
            - "8989:80"
        volumes:
            - ./config:/var/www/html/config
            - ./custom:/var/www/html/custom
        restart: unless-stopped

    mysql:
        image: mariadb:11.5.2
        environment:
            MYSQL_ROOT_PASSWORD: aPUo56ZCWR
            MYSQL_DATABASE: techebttracker
            MYSQL_USER: techebt
            MYSQL_PASSWORD: aPUo56ZCWR
        volumes:
            - ./mysql:/var/lib/mysql
        restart: always