version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v3.3.1
    container_name: prometheus
    volumes:
      - /mnt/DriveDATA/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /mnt/DriveDATA/prometheus:/prometheus
      - /etc/localtime:/etc/localtime:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
        #- '--web.external-url=https://prom.teche.ai/'
        #- '--web.route-prefix='
    ports:
      - "8229:9090"
    networks:
      - monitoring
    restart: unless-stopped

  grafana:
    image: grafana/grafana:12.0.0
    container_name: grafana
    volumes:
      - /mnt/DriveDATA/grafana:/var/lib/grafana
      - /mnt/DriveDATA/grafana/alerting:/etc/grafana/provisioning/alerting
    ports:
      - "8230:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=https://changeme-url
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=your-email@gmail.com
      - GF_SMTP_PASSWORD=your-app-password
      - GF_SMTP_FROM_ADDRESS=your-email@gmail.com
      - GF_SMTP_FROM_NAME=Grafana
      - GF_SMTP_SKIP_VERIFY=false
    networks:
      - monitoring
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8231:8080"
    networks:
      - monitoring
    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter:v1.9.1
    container_name: node_exporter
    ports:
      - "8232:9100"
    networks:
      - monitoring
    restart: unless-stopped
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "9104:3100"   # expose Loki on host port 9104
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - /mnt/DriveDATA/loki:/loki
      - /mnt/DriveDATA/loki/loki-config.yml:/etc/loki/loki-config.yml
    restart: unless-stopped
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - /var/log:/var/log                       # host logs
      - /mnt/DriveDATA/promtail/promtail-config.yml:/etc/promtail/config.yml
      - /mnt/DriveDATA/promtail:/tmp            # promtail positions
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped

networks:
  monitoring: